name: "deploy to aws"

on: 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "checkout code"
        uses: actions/checkout@v2

      - name: "setup nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "install dependencies"
        run: npm install

      - name: "install pm2 globally"
        run: npm install pm2 -g

      - name: "run the tests"
        run: npm test

      - name: "deploy to aws"
        run: pm2 start src/index.js
